Repository Solvro/web-eventownik-v2, pull requests merged in 2025-03, with the labels that each got.

#29 Participants table
  package-lock.json
  package.json
  src/app/dashboard/events/[id]/participants/actions.ts
  src/app/dashboard/events/[id]/participants/page.tsx
  src/app/dashboard/events/[id]/participants/table/action-components.tsx
  src/app/dashboard/events/[id]/participants/table/attribute-input.tsx
  src/app/dashboard/events/[id]/participants/table/columns.tsx
  src/app/dashboard/events/[id]/participants/table/data.ts
  src/app/dashboard/events/[id]/participants/table/edit-participant-form.tsx
  src/app/dashboard/events/[id]/participants/table/mocked-data.ts
  src/app/dashboard/events/[id]/participants/table/participants-table.tsx
  src/app/dashboard/events/[id]/participants/table/utils.tsx
  src/app/dashboard/events/page.tsx
  src/app/globals.css
  src/components/ui/alert-dialog.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/select.tsx
  src/components/ui/table.tsx
  src/types/attributes.ts
  src/types/participant.ts
Labels: enhancement

#30 Podstawowa rejestracja na wydarzenie
  .env.example
  .github/workflows/ci.yml
  next.config.ts
  package-lock.json
  package.json
  src/app/[eventSlug]/actions.ts
  src/app/[eventSlug]/page.tsx
  src/app/[eventSlug]/register-participant-form.tsx
  src/app/auth/actions.ts
  src/app/dashboard/events/[id]/participants/table/edit-participant-form.tsx
  src/components/app-logo.tsx
  src/components/attribute-input.tsx
  src/lib/api.ts
  src/lib/utils.ts
  src/middleware.ts
  src/types/.gitkeep
  src/types/event.ts
  src/types/form.ts
  src/types/schemas.ts
Labels: size/L

#31 fix: fix image position on form page
  src/app/[eventSlug]/page.tsx
Labels: size/XS

#32 fix: temporary use color attribute as textarea
  src/components/attribute-input.tsx
  src/lib/utils.ts
Labels: size/S

#33 feat: seo at layout and dynamic metadata on event sites
  package-lock.json
  src/app/[eventSlug]/page.tsx
  src/app/auth/layout.tsx
  src/app/dashboard/layout.tsx
  src/app/layout.tsx
Labels: enhancement, size/M

#34 fix: info after submitting form and form labels on error
  src/app/[eventSlug]/actions.ts
  src/app/[eventSlug]/register-participant-form.tsx
  src/components/ui/form.tsx
  src/types/event.ts
Labels: size/M

#36 chore: remove toast after successful submitting form
  src/app/[eventSlug]/register-participant-form.tsx
Labels: size/S

#35 fix: login automatically after registration
  src/app/auth/actions.ts
  src/app/auth/register/page.tsx
Labels: size/S

#37 fix: make section form field multiple select
  src/app/[eventSlug]/actions.ts
  src/app/[eventSlug]/register-participant-form.tsx
  src/components/attribute-input.tsx
  src/components/ui/input.tsx
  src/lib/utils.ts
Labels: size/L

#39 fix: make having brain optional
  src/lib/utils.ts
Labels: size/XS

#13 Event creation view
  next.config.ts
  src/app/dashboard/(create-event)/(steps)/attributes.tsx
  src/app/dashboard/(create-event)/(steps)/coorganizers.tsx
  src/app/dashboard/(create-event)/(steps)/general-info.tsx
  src/app/dashboard/(create-event)/(steps)/personalization.tsx
  src/app/dashboard/(create-event)/actions.ts
  src/app/dashboard/(create-event)/create-event-form.tsx
  src/app/dashboard/(create-event)/form-container.tsx
  src/app/dashboard/(create-event)/state.ts
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/components/providers.tsx
  src/components/ui/select.tsx
Labels: size/XXL

#40 fix: form overflowing but not overflowing
  src/app/[eventSlug]/page.tsx
Labels: size/XS

#43 fix: add 'engines' to package.json
  package.json
Labels: size/XS

#44 fix: add proper handling of empty 'event.image'
  src/app/dashboard/(create-event)/(steps)/attributes.tsx
  src/app/dashboard/(create-event)/actions.ts
Labels: size/XS

#45 feat: creating forms according to new schema
  src/app/[eventSlug]/page.tsx
  src/app/dashboard/events/[id]/forms/(steps)/attributes.tsx
  src/app/dashboard/events/[id]/forms/(steps)/general-info.tsx
  src/app/dashboard/events/[id]/forms/actions.ts
  src/app/dashboard/events/[id]/forms/create-event-form-form.tsx
  src/app/dashboard/events/[id]/forms/data-access.ts
  src/atoms/new-event-form-atom.ts
  src/components/ui/alert.tsx
  src/types/attributes.ts
  src/types/forms.ts
Labels: size/XL

#46 fix: multiple fixes for Linek
  public/logo-dark.svg
  public/logo-light.svg
  src/app/[eventSlug]/page.tsx
  src/app/dashboard/(create-event)/(steps)/attributes.tsx
  src/app/dashboard/(create-event)/(steps)/general-info.tsx
  src/app/dashboard/(create-event)/actions.ts
  src/app/dashboard/(create-event)/state.ts
  src/components/app-logo.tsx
  src/components/attribute-input.tsx
  src/lib/utils.ts
  src/types/attributes.ts
  src/types/event.ts
Labels: size/L

#42 feat: event view
  src/app/dashboard/events/[id]/page.tsx
  src/types/event.ts
Labels: enhancement, size/M

#47 fix: add y gap in event public view
  src/app/[eventSlug]/page.tsx
  src/app/dashboard/events/[id]/page.tsx
Labels: size/S

#51 feat: add event settings page [WiP]
  .env.example
  .github/workflows/ci.yml
  .gitignore
  package-lock.json
  package.json
  src/app/[eventSlug]/page.tsx
  src/app/dashboard/(create-event)/(steps)/attributes.tsx
  src/app/dashboard/events/[id]/page.tsx
  src/app/dashboard/events/[id]/settings/actions.ts
  src/app/dashboard/events/[id]/settings/page.tsx
  src/app/dashboard/events/[id]/settings/settings-tabs.tsx
  src/app/dashboard/events/[id]/settings/tabs/attributes.tsx
  src/app/dashboard/events/[id]/settings/tabs/coorganizers.tsx
  src/app/dashboard/events/[id]/settings/tabs/general-info.tsx
  src/app/dashboard/events/[id]/settings/tabs/personalization.tsx
  src/app/dashboard/events/[id]/settings/tabs/tab-props.ts
  src/app/dashboard/events/page.tsx
  src/components/ui/toast.tsx
  src/lib/api.ts
  src/lib/utils.ts
  src/types/event.ts
Labels: size/XXL

#56 feat: small tweaks
  README.md
  package-lock.json
  package.json
  public/favicon.ico
Labels: size/XS

#58 Update dependencies
  package-lock.json
  package.json
  postcss.config.mjs
  src/app/[eventSlug]/page.tsx
  src/app/[eventSlug]/register-participant-form.tsx
  src/app/dashboard/(create-event)/(steps)/attributes.tsx
  src/app/dashboard/(create-event)/(steps)/coorganizers.tsx
  src/app/dashboard/events/[id]/forms/(steps)/attributes.tsx
  src/app/dashboard/events/[id]/forms/[formId]/edit-form.tsx
  src/app/dashboard/events/[id]/forms/create-event-form-form.tsx
  src/app/dashboard/events/[id]/participants/table/action-components.tsx
  src/app/dashboard/events/[id]/participants/table/participants-table.tsx
  src/app/dashboard/events/[id]/settings/settings-tabs.tsx
  src/app/dashboard/events/[id]/settings/tabs/general-info.tsx
  src/app/dashboard/events/[id]/settings/tabs/personalization.tsx
  src/app/dashboard/events/page.tsx
  src/app/globals.css
  src/components/attribute-input.tsx
  src/components/dashboard-sidebar.tsx
  src/components/event-info-block.tsx
  src/components/navbar.tsx
  src/components/theme-switch.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/alert.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/dialog.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/popover.tsx
  src/components/ui/select.tsx
  src/components/ui/switch.tsx
  src/components/ui/table.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  tailwind.config.ts
Labels: size/L

#52 feat: add export functionality for event participants
  src/app/dashboard/events/[id]/participants/actions.ts
  src/app/dashboard/events/[id]/participants/table/export-button.tsx
  src/app/dashboard/events/[id]/participants/table/participants-table.tsx
Labels: size/L

#53 feat: add event settings co organizers page [WiP]
  next.config.ts
  package-lock.json
  package.json
  src/app/dashboard/events/[id]/settings/actions.ts
  src/app/dashboard/events/[id]/settings/page.tsx
  src/app/dashboard/events/[id]/settings/settings-tabs.tsx
  src/app/dashboard/events/[id]/settings/tabs/co-organizers.tsx
  src/app/dashboard/events/[id]/settings/tabs/coorganizers.tsx
  src/app/dashboard/events/[id]/settings/tabs/personalization.tsx
  src/app/dashboard/events/[id]/settings/tabs/tab-props.ts
  src/app/globals.css
  src/types/co-organizer.ts
Labels: size/XL

#59 fix: use new schema for sending forms
  src/app/[eventSlug]/actions.ts
Labels: size/XS

#61 feat: add event settings attributes tab
  src/app/dashboard/(create-event)/state.ts
  src/app/dashboard/events/[id]/settings/actions.ts
  src/app/dashboard/events/[id]/settings/page.tsx
  src/app/dashboard/events/[id]/settings/settings-tabs.tsx
  src/app/dashboard/events/[id]/settings/tabs/attributes.tsx
  src/app/dashboard/events/[id]/settings/tabs/tab-props.ts
  src/components/attribute-input.tsx
  src/components/ui/select.tsx
  src/lib/utils.ts
  src/types/attributes.ts
Labels: size/XL

#63 feat: new old landing page and hide some navbar elements
  src/app/page.tsx
  src/components/navbar.tsx
Labels: size/M

#64 fix: make `FormContainer` scrollable
  src/app/dashboard/(create-event)/form-container.tsx
Labels: size/XS

#65 fix: enable saving forms in the edit page without changing dates and save selected attributes
  src/app/dashboard/events/[id]/forms/(steps)/attributes.tsx
  src/app/dashboard/events/[id]/forms/[formId]/edit-form.tsx
  src/app/dashboard/events/[id]/forms/actions.ts
  src/types/attributes.ts
  src/types/forms.ts
Labels: size/M

#66 feat: event sharing
  package-lock.json
  package.json
  src/app/dashboard/events/[id]/page.tsx
  src/components/ui/share-button.tsx
Labels: size/M

#67 (Participants table) Fix selecting rows and change edit-form view in table
  src/app/dashboard/events/[id]/participants/table/columns.tsx
  src/app/dashboard/events/[id]/participants/table/edit-participant-form.tsx
  src/app/dashboard/events/[id]/participants/table/participants-table.tsx
  src/components/ui/table.tsx
  src/types/participant.ts
Labels: size/S

#60 feat: create page for next event forms
  src/app/[eventSlug]/[formSlug]/[userId]/actions.ts
  src/app/[eventSlug]/[formSlug]/[userId]/form-generator.tsx
  src/app/[eventSlug]/[formSlug]/[userId]/page.tsx
Labels: size/L

#62 feat: mails
  package-lock.json
  package.json
  src/app/dashboard/events/[id]/emails/(steps)/message-content.tsx
  src/app/dashboard/events/[id]/emails/(steps)/trigger-type.tsx
  src/app/dashboard/events/[id]/emails/actions.ts
  src/app/dashboard/events/[id]/emails/create-email-template-form.tsx
  src/app/dashboard/events/[id]/emails/data-access.ts
  src/app/dashboard/events/[id]/emails/delete-email-popup.tsx
  src/app/dashboard/events/[id]/emails/page.tsx
  src/app/dashboard/events/[id]/emails/template-entry.tsx
  src/app/dashboard/events/[id]/inbox/page.tsx
  src/app/dashboard/events/[id]/participants/actions.ts
  src/app/dashboard/events/[id]/participants/page.tsx
  src/app/dashboard/events/[id]/participants/table/participants-table.tsx
  src/app/dashboard/events/[id]/participants/table/send-mail-form.tsx
  src/app/dashboard/events/[id]/send/page.tsx
  src/app/globals.css
  src/atoms/new-email-template-atom.ts
  src/components/dashboard-sidebar.tsx
  src/components/ui/radio-group.tsx
  src/lib/emails.ts
  src/types/emails.ts
Labels: size/XXL

#69 Fix/a few fixes
  package-lock.json
  package.json
  src/app/dashboard/events/[id]/settings/tabs/attributes.tsx
  src/app/dashboard/events/page.tsx
  src/app/layout.tsx
  src/components/ui/share-button.tsx
Labels: size/L

#70 fix: adding option when no options in attributes settings page
  src/app/dashboard/events/[id]/settings/tabs/attributes.tsx
Labels: size/XS

#68 Allow optional fields and handle multiselect in participants table
  src/app/[eventSlug]/[formSlug]/[userId]/form-generator.tsx
  src/app/dashboard/events/[id]/forms/actions.ts
  src/app/dashboard/events/[id]/participants/actions.ts
  src/app/dashboard/events/[id]/participants/table/edit-participant-form.tsx
  src/atoms/new-event-form-atom.ts
  src/components/attribute-input-file.tsx
  src/components/attribute-input.tsx
  src/lib/utils.ts
  src/types/attributes.ts
  src/types/event.ts
  src/types/form.ts
Labels: size/L

#71 feat(mails): add mail editing and mail history
  src/app/dashboard/events/[id]/emails/(steps)/message-content.tsx
  src/app/dashboard/events/[id]/emails/(steps)/trigger-type.tsx
  src/app/dashboard/events/[id]/emails/(table)/columns.tsx
  src/app/dashboard/events/[id]/emails/(table)/table.tsx
  src/app/dashboard/events/[id]/emails/[emailId]/edit-form.tsx
  src/app/dashboard/events/[id]/emails/[emailId]/page.tsx
  src/app/dashboard/events/[id]/emails/actions.ts
  src/app/dashboard/events/[id]/emails/data-access.ts
  src/app/dashboard/events/[id]/emails/mail-history-popup.tsx
  src/app/dashboard/events/[id]/emails/template-entry.tsx
  src/components/editor-menu-bar.tsx
  src/components/editor.tsx
  src/types/emails.ts
Labels: size/XXL

#73 feat: add top loading bar
  package-lock.json
  package.json
  src/app/layout.tsx
Labels: size/XS

#74 feat: show createdAt in participants table
  src/app/dashboard/events/[id]/participants/table/columns.tsx
  src/app/dashboard/events/[id]/participants/table/participants-table.tsx
Labels: size/S

#75 feat: implement deleting events, improve form edit dark mode
  src/app/dashboard/(create-event)/(steps)/general-info.tsx
  src/app/dashboard/events/[id]/forms/[formId]/edit-form.tsx
  src/app/dashboard/events/[id]/settings/actions.ts
  src/app/dashboard/events/[id]/settings/settings-tabs.tsx
Labels: size/L

#76 feat: participants numbering and mobile improvements
  src/app/dashboard/events/[id]/layout.tsx
  src/app/dashboard/events/[id]/participants/page.tsx
  src/app/dashboard/events/[id]/participants/table/columns.tsx
  src/app/dashboard/events/[id]/participants/table/participants-table.tsx
  src/app/dashboard/events/[id]/settings/settings-tabs.tsx
  src/app/dashboard/events/[id]/settings/tabs/general-info.tsx
  src/app/dashboard/events/[id]/settings/tabs/personalization.tsx
  src/components/dashboard-sidebar.tsx
Labels: size/L

#78 fix: mobile improvements
  src/app/dashboard/events/[id]/participants/table/download-file-attribute-button.tsx
  src/app/dashboard/events/[id]/settings/tabs/attributes.tsx
  src/app/dashboard/events/[id]/settings/tabs/co-organizers.tsx
  src/app/dashboard/events/[id]/settings/tabs/general-info.tsx
  src/app/dashboard/events/[id]/settings/tabs/personalization.tsx
  src/types/attributes.ts
Labels: size/L
