Repository Solvro/web-eventownik-v2, pull requests merged in 2025-04, with the labels that each got.

#80 fix: fix dialog animation
  package-lock.json
  package.json
  src/app/dashboard/events/[id]/settings/settings-tabs.tsx
  src/app/dashboard/layout.tsx
  src/app/globals.css
  src/components/ui/alert-dialog.tsx
  src/components/ui/dialog.tsx
Labels: size/M

#95 feat: add dynamic email title placeholder
  src/app/dashboard/events/[id]/emails/(steps)/message-content.tsx
Labels: size/S

#96 feat: add contact email to settings
  src/app/dashboard/events/[id]/settings/actions.ts
  src/app/dashboard/events/[id]/settings/tabs/personalization.tsx
  src/types/event.ts
Labels: size/M

#94 refactor: change table component markup
  src/app/dashboard/events/[id]/emails/(table)/table.tsx
  src/app/dashboard/events/[id]/participants/table/participants-table.tsx
  src/components/ui/table.tsx
Labels: size/L

#93 feat: add select for attributes and forms in email trigger configurator
  src/app/dashboard/events/[id]/emails/(steps)/trigger-type.tsx
  src/app/dashboard/events/[id]/emails/[emailId]/edit-form.tsx
  src/app/dashboard/events/[id]/emails/[emailId]/page.tsx
  src/app/dashboard/events/[id]/emails/create-email-template-form.tsx
  src/app/dashboard/events/[id]/emails/data-access.ts
  src/app/dashboard/events/[id]/emails/delete-email-popup.tsx
  src/app/dashboard/events/[id]/emails/mail-history-popup.tsx
  src/app/dashboard/events/[id]/emails/page.tsx
  src/app/dashboard/events/[id]/emails/template-entry.tsx
  src/components/ui/select.tsx
  src/lib/emails.ts
Labels: size/L

#100 fix: align card heights
  src/app/dashboard/events/page.tsx
Labels: size/S

#99 feat: add mass participant deletion
  src/app/dashboard/events/[id]/participants/actions.ts
  src/app/dashboard/events/[id]/participants/table/action-components.tsx
  src/app/dashboard/events/[id]/participants/table/participants-table.tsx
Labels: size/L

#102 Linki na stronie wydarzenia
  package-lock.json
  package.json
  src/app/[eventSlug]/[formSlug]/[userId]/page.tsx
  src/app/[eventSlug]/page.tsx
  src/app/dashboard/events/[id]/page.tsx
  src/app/dashboard/events/page.tsx
  src/components/share-button.tsx
  src/components/ui/tooltip.tsx
Labels: size/L

#98 fix: event creation form improvements
  src/app/dashboard/(create-event)/(steps)/attributes.tsx
  src/app/dashboard/(create-event)/(steps)/coorganizers.tsx
  src/app/dashboard/(create-event)/(steps)/general-info.tsx
  src/app/dashboard/(create-event)/(steps)/personalization.tsx
  src/app/dashboard/(create-event)/actions.ts
  src/app/dashboard/(create-event)/state.ts
  src/app/dashboard/events/[id]/forms/[formId]/edit-form.tsx
  src/app/dashboard/events/[id]/settings/tabs/attributes.tsx
  src/lib/utils.ts
Labels: size/XL

#110 fix: fix form not forming
  src/app/dashboard/events/[id]/forms/[formId]/edit-form.tsx
  src/app/dashboard/events/[id]/forms/actions.ts
Labels: size/M

#108 feat(dashboard): blocks
  src/app/dashboard/events/[id]/blocks/[blockId]/(table)/columns.tsx
  src/app/dashboard/events/[id]/blocks/[blockId]/(table)/table.tsx
  src/app/dashboard/events/[id]/blocks/[blockId]/add-block-entry.tsx
  src/app/dashboard/events/[id]/blocks/[blockId]/block-entry.tsx
  src/app/dashboard/events/[id]/blocks/[blockId]/block-participants-popup.tsx
  src/app/dashboard/events/[id]/blocks/[blockId]/delete-block-popup.tsx
  src/app/dashboard/events/[id]/blocks/[blockId]/edit-block-entry.tsx
  src/app/dashboard/events/[id]/blocks/[blockId]/page.tsx
  src/app/dashboard/events/[id]/blocks/actions.ts
  src/app/dashboard/events/[id]/layout.tsx
  src/components/dashboard-sidebar.tsx
  src/types/blocks.ts
Labels: size/XL

#101 fix: attributes in form creation
  src/app/dashboard/events/[id]/forms/(steps)/attributes.tsx
  src/app/dashboard/events/[id]/forms/(steps)/general-info.tsx
  src/app/dashboard/events/[id]/forms/[formId]/edit-form.tsx
  src/app/dashboard/events/[id]/forms/actions.ts
  src/atoms/new-event-form-atom.ts
  src/components/attributes-manager.tsx
Labels: size/XL

#113 fix: use file input in next forms too
  src/app/[eventSlug]/[formSlug]/[userId]/actions.ts
  src/app/[eventSlug]/[formSlug]/[userId]/form-generator.tsx
  src/app/[eventSlug]/actions.ts
  src/app/[eventSlug]/register-participant-form.tsx
Labels: size/M

#107 105 select displayed attributes
  package-lock.json
  package.json
  src/app/dashboard/events/[id]/settings/tabs/attributes.tsx
  src/components/ui/badge.tsx
  src/components/ui/command.tsx
  src/components/ui/multi-select.tsx
  src/components/ui/separator.tsx
Labels: size/XL

#109 Refactor/fixes in participants table
  src/app/dashboard/events/[id]/participants/actions.ts
  src/app/dashboard/events/[id]/participants/page.tsx
  src/app/dashboard/events/[id]/participants/table/action-components.tsx
  src/app/dashboard/events/[id]/participants/table/columns.tsx
  src/app/dashboard/events/[id]/participants/table/data.ts
  src/app/dashboard/events/[id]/participants/table/edit-participant-form.tsx
  src/app/dashboard/events/[id]/participants/table/participants-table.tsx
  src/app/dashboard/events/[id]/participants/table/table-menu.tsx
  src/app/dashboard/events/[id]/participants/table/table-row-form.tsx
  src/app/dashboard/events/[id]/participants/table/utils.tsx
  src/components/attribute-input.tsx
  src/types/participant.ts
Labels: size/XL

#115 Feat/blocks in participants table
  src/app/dashboard/events/[id]/participants/actions.ts
  src/app/dashboard/events/[id]/participants/page.tsx
  src/app/dashboard/events/[id]/participants/table/columns.tsx
  src/app/dashboard/events/[id]/participants/table/participants-table.tsx
  src/app/dashboard/events/[id]/participants/table/table-row-form.tsx
  src/app/dashboard/events/[id]/participants/table/utils.tsx
  src/components/attribute-input.tsx
Labels: size/L

#114 feat(participant): blocks
  package-lock.json
  package.json
  src/app/[eventSlug]/[formSlug]/[userId]/actions.ts
  src/app/[eventSlug]/[formSlug]/[userId]/form-generator.tsx
  src/app/[eventSlug]/[formSlug]/[userId]/page.tsx
  src/components/attribute-blocks-wrapper.tsx
  src/components/attribute-input-block.tsx
  src/components/attribute-input.tsx
  src/components/ui/accordion.tsx
  src/types/attributes.ts
  src/types/blocks.ts
  src/types/participant.ts
Labels: size/L

#116 feat: implement pulling blocks in form
  src/app/[eventSlug]/[formSlug]/[userId]/actions.ts
  src/app/[eventSlug]/[formSlug]/[userId]/form-generator.tsx
  src/app/[eventSlug]/[formSlug]/[userId]/page.tsx
  src/app/[eventSlug]/register-participant-form.tsx
  src/components/attribute-blocks-wrapper.tsx
  src/components/attribute-input-block.tsx
  src/components/attribute-input.tsx
Labels: size/L

#117 feat(forms): replace textarea with wysiwyg editor; editor tweaks
  package-lock.json
  package.json
  src/app/[eventSlug]/[formSlug]/[userId]/page.tsx
  src/app/dashboard/events/[id]/emails/(steps)/message-content.tsx
  src/app/dashboard/events/[id]/emails/[emailId]/edit-form.tsx
  src/app/dashboard/events/[id]/forms/(steps)/general-info.tsx
  src/app/dashboard/events/[id]/forms/[formId]/edit-form.tsx
  src/components/editor-menu-bar.tsx
  src/components/editor.tsx
Labels: size/L

#118 feat: add "add to calendar" button and improve social links
  package-lock.json
  package.json
  src/app/[eventSlug]/[formSlug]/[userId]/page.tsx
  src/app/[eventSlug]/page.tsx
  src/app/dashboard/events/[id]/page.tsx
  src/components/add-to-calendar-button.tsx
  src/components/event-info-div.tsx
  src/components/social-media-link.tsx
Labels: size/L
