Repository Solvro/web-eventownik-v2, pull requests merged in 2025-07, with the labels that each got.

#141 135-Zmiana-domyślnego-zdjęcia-wydarzenia-na-z-logiem-Solvro
  package-lock.json
  package.json
  public/event-photo-placeholder.png
Labels: size/XS

#145 Strona z info że do dashboardu potrzeba się zalogować #111
  src/app/auth/login/page.tsx
  src/app/auth/register/page.tsx
  src/components/ui/alert.tsx
  src/middleware.ts
Labels: size/L

#154 (Participants table) Change search behaviour to be more intuitive
  src/app/dashboard/events/[id]/participants/table/table-menu.tsx
Labels: size/M
